# Generated by Django 4.2.29 on 2026-04-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_ancvisit_options_alter_smslog_options_and_more'),
        ('reminders', '0002_smslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminderlog',
            options={'ordering': ['-date_sent']},
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='accounts.patientprofile'),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ancvisit'),
        ),
        migrations.DeleteModel(
            name='SMSLog',
        ),
    ]
