# Generated by Django 6.0.2 on 2026-02-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientprofile_address_patientprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='edd',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='pregnancy_period',
            field=models.PositiveIntegerField(blank=True, help_text='Current duration of pregnancy in weeks', null=True),
        ),
    ]
