# Generated by Django 6.0.2 on 2026-02-16 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientprofile_edd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'Staff Profile', 'verbose_name_plural': 'Staff Profiles'},
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='e.g. Obstetrics, Midwifery', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(help_text='Unique Hospital Employee ID', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='ANCVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.PositiveIntegerField()),
                ('scheduled_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anc_visits', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
    ]
