# Generated by Django 6.0.2 on 2026-02-17 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_staffprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='ward_number',
            field=models.CharField(default='ANC Ward A', help_text='Assigned hospital ward', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
