# Generated by Django 6.0.2 on 2026-03-09 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_patientprofile_ward_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
