# Generated by Django 6.0.2 on 2026-03-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_patientprofile_assigned_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='email_alerts_active',
            field=models.BooleanField(default=True, help_text='Admin control to start/stop the high-frequency email loop for this patient'),
        ),
    ]
