# Generated by Django 4.2.29 on 2026-04-03 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_smslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ancvisit',
            options={'ordering': ['visit_number']},
        ),
        migrations.AlterModelOptions(
            name='smslog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='ancvisit',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='edd',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='last_menstrual_period',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='next_of_kin_phone',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='clinical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ATTENDED', 'Attended'), ('MISSED', 'Missed'), ('APPROVED', 'Approved')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='visit_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True, default='N/A'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='email_alerts_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='pregnancy_period',
            field=models.IntegerField(default=0, help_text='Weeks pregnant at registration'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='ward_number',
            field=models.CharField(blank=True, default='ANC-01', max_length=20),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='accounts.patientprofile'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='response_body',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(default='Antenatal Care', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PATIENT', 'Patient')], max_length=20, null=True),
        ),
    ]
